# a,b=5,2
# print(a<b)
# print(a>b)
# print(a<=b)
# print(a>=b)
# print(a==b)
# print(a!=b)
# c="trevin123"
# print(type(c))
# name=input("enter your name")
# print(name)
# print(123)
# print("trevin")
# print(a)
# name=input("enter your name")
# age=input("enter your age")
# print("hi i am",name,"i am",age,"old")
# print(type(name))
# print(type(age))

# a=int(input("enter the first number"))
# b=int(input("enter the second number"))
# print(a+b)
# a=20
# b=21.5
# c=1+3j
# print(type(a))
# print(type(b))
# print(type(c))
# a="trevin"
# print(type(a))
# print(a*5)
# print(a[0])
# print(a[4])
# b=len(a)
# print(b)
# print(a[b-1])
# print(a[-1])
# print('v' in a)
# list1=[5,4,6,8,3]
# list2=["trevin",15,"bahrain","sacred heart school"]
# print(list1)
# print(list2)
# print(type(list1))
# print(list2[2])
# print(list2[-1])
# list2[2]="sri lanka"
# print(list2)
# list2.append("grade 11")
# print(list2)
# list2.insert(2,51110344)
# print(list2)
# print(list2[0:3])
# print(list2[2:5])
# list3=["roshan","rebbeca","Amanda","deandra","trevin"]
# print(list2+list3)
# list4=list2+list3
# print(list4)
# list4.remove("grade 11")
# print(list4)
# del(list4)
# tup1=("controller","Keyboard","mouse")
# print(type(tup1))
# print(tup1)
# print(tup1[1])
# print(tup1)
# c=list(tup1)
# c.append("moniter")
# print(c)
# print(type(c))
# tup1=tuple(c)
# print(type(tup1))
# list2.insert(2,1005)
# print(list2)
# list2.append("five")
# print(list2)
# print(list2[0:5])
# a="fredrick"
# print(a[0]) 
# b=len(a)
# print(b)
# print('e' in a)
# list5=("i am 15 years old")
# b=len(list5)
# print(b)
# print(list5[-1])
# print(type(list5))
# list6=["i live in bahrain"]
# print(type(list6))
# list6.append("but i am from sri lanka")
# print(list6)
# print(list6[0:2])
# list6.insert(3,505)
# print(list6)
# b=len(list6)
# print(b)
# list6.insert(1,909)
# print(list6)
# print(list6[2])
# print(list6[-1])
# list6.remove("but i am from sri lanka")
# print(list6)
# tup2=("eleven","forty five","ten")
# c=list(tup2)
# print(type(tup2))
dict1={"name":"trevin","age":15,"place":"sri lanka"}
print(dict1)
mobile={"brand":"apple","type":"iphone 13","memory":"256 GB","camera":"ultra 4K resolution"}
print(mobile)
print(mobile["memory"])
mobile["price"]=1095
print(mobile)
mobile["memory"]="128 GB"
print(mobile)
del(mobile["camera"])
print(mobile)
set1={25,44,37,10,37}
print(set1)

